data:extend{
    {
        type = "virtual-signal",
        name = "Ammo-Warning",
        icon = "__Compaction2__/graphics/alerts/ammo-icon-red.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Danger-Warning",
        icon = "__Compaction2__/graphics/alerts/danger-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Destroyed-Warning",
        icon = "__Compaction2__/graphics/alerts/destroyed-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Electricity-Warning",
        icon = "__Compaction2__/graphics/alerts/electricity-icon-red.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Electricity-Unplugged-Warning",
        icon = "__Compaction2__/graphics/alerts/electricity-icon-unplugged.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Fluid-Warning",
        icon = "__Compaction2__/graphics/alerts/fluid-icon-red.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Fuel-Warning",
        icon = "__Compaction2__/graphics/alerts/fuel-icon-red.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Logistic-Delivery-Warning",
        icon = "__Compaction2__/graphics/alerts/logistic-delivery.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Material-Warning",
        icon = "__Compaction2__/graphics/alerts/no-building-material-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Storage-Warning",
        icon = "__Compaction2__/graphics/alerts/no-storage-space-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Construction-Warning",
        icon = "__Compaction2__/graphics/alerts/not-enough-construction-robots-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Repair-Warning",
        icon = "__Compaction2__/graphics/alerts/not-enough-repair-packs-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Recharge-Warning",
        icon = "__Compaction2__/graphics/alerts/recharge-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Too-Far-Warning",
        icon = "__Compaction2__/graphics/alerts/too-far-from-roboport-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "Warning",
        icon = "__Compaction2__/graphics/alerts/warning-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    },
    {
        type = "virtual-signal",
        name = "No-Path",
        icon = "__Compaction2__/graphics/alerts/no-path-icon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "alerts-special",
    }
}